version: '3.8'
services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    ports:
      - "5432:5432"

  airflow-webserver:
    image: apache/airflow:2.7.1
    depends_on:
      - postgres
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      # เพิ่ม requests เข้าไปเพื่อให้ Python ยิง Webhook 
      - _PIP_ADDITIONAL_REQUIREMENTS=feedparser pandas psycopg2-binary requests
    ports:
      - "8080:8080"
    # บังคับ init db ก่อนเปิด webserver
    command: bash -c "airflow db init && airflow webserver"
    volumes:
      - ./dags:/opt/airflow/dags

  airflow-scheduler:
    image: apache/airflow:2.7.1
    depends_on:
      - postgres
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      # ต้องใส่ที่นี่ด้วย เพราะ Scheduler คือตัวรันโค้ด Python ใน DAG 
      - _PIP_ADDITIONAL_REQUIREMENTS=feedparser pandas psycopg2-binary requests
    # บังคับรอให้ db พร้อมแล้วเปิด scheduler
    command: scheduler
    volumes:
      - ./dags:/opt/airflow/dags