version: '3.8'
services:
 #1. PostgreSQL database for storing news.
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    ports:
      - "5432:5432"

 #2. Apache Airflow (Pipeline Manager)
  airflow-webserver:
    image: apache/airflow:2.7.1
    # เพิ่มส่วนนี้เพื่อบังคับลง Library ทุกครั้งที่เครื่องติด
    entrypoint: >
      bash -c "pip install feedparser pandas tabulate && airflow db upgrade && airflow webserver"
    depends_on:
      - postgres
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags

  airflow-scheduler:
    image: apache/airflow:2.7.1
    # เพิ่มส่วนนี้เหมือนกันเพื่อให้หัวใจหลักมองเห็น Library ด้วย
    entrypoint: >
      bash -c "pip install feedparser pandas tabulate && airflow scheduler"
    depends_on:
      - postgres
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    volumes:
      - ./dags:/opt/airflow/dags