import sqlite3
import os
import requests

# ตั้งค่า Discord
DISCORD_WEBHOOK_URL = "https://discord.com/api/webhooks/1478580196314452050/Rbo7zMAcUw3csQWV5mpoj3JCSBDtjRLbkvTw69H5G1OC18yKgx59-QR3fFtKlE_rPA7t"

BASE_PATH = os.path.dirname(os.path.abspath(__file__))
DB_NAME = os.path.join(BASE_PATH, "disaster.db")

def send_discord_alert(title, severity_score, province):
    """ส่งผลการวิเคราะห์เข้า Discord"""
    # กำหนดสีตามคะแนน (แดง=4+, ส้ม=2+, เหลือง=1)
    if severity_score >= 4:
        color = 15158332
        label = "High"
    elif severity_score >= 2:
        color = 15105570
        label = "Medium"
    else:
        color = 16776960
        label = "Low"
    
    payload = {
        "username": "Warning Center",
        "avatar_url": "https://cdn-icons-png.flaticon.com/512/564/564619.png",
        "embeds": [{
            "title": "📊 สรุปรายงานภัยพิบัติ",
            "description": f"**จังหวัด:** {province}\n**หัวข้อ:** {title}\n**ระดับความรุนแรง:** {label}",
            "color": color,
            "footer": {"text": "Generated by report.py"}
        }]
    }
    try:
        requests.post(DISCORD_WEBHOOK_URL, json=payload)
    except: pass


def calculate_severity(title):
    score = 0
    if "เสียชีวิต" in title: score += 2
    if "บาดเจ็บ" in title: score += 1
    if "อพยพด่วน" in title: score += 1
    if "เสียหายหนัก" in title: score += 1
    if "เตือนภัย" in title: score += 1
    return min(max(score, 1), 5)

# ✨ ฟังก์ชันใหม่: แปลงคะแนนเป็น สี และ ระดับข้อความ
def get_severity_display(score):
    if score >= 4:
        return "🔴 ระดับวิกฤต (High)"
    elif score >= 2:
        return "🟠 ระดับปานกลาง (Medium)"
    else:
        return "🟡 ระดับเฝ้าระวัง (Low)"

def generate_summary():
    if not os.path.exists(DB_NAME): return
    conn = sqlite3.connect(DB_NAME)
    c = conn.cursor()
    c.execute("""
        SELECT n.title, p.name_th
        FROM news n
        LEFT JOIN provinces p ON n.province_id = p.id
        WHERE n.title LIKE '%แผ่นดินไหว%' OR n.title LIKE '%น้ำท่วม%'
    """)
    rows = c.fetchall()
    conn.close()

    if not rows: return

    for title, province in rows:
        province_name = province if province else "ไม่ระบุจังหวัด"
        severity_score = calculate_severity(title)
        # ส่งเข้า Discord
        send_discord_alert(title, severity_score, province_name)
        print(f"✅ Sent alert for: {province_name}")

if __name__ == "__main__":
    generate_summary()